# Generated by Django 5.0.3 on 2024-03-25 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpn',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_bike_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
