# Generated by Django 5.0.6 on 2024-05-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_userprofile_age_userprofile_cpn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_bike_owner',
        ),
    ]
