# Generated by Django 5.0.6 on 2024-05-11 19:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_userprofile_is_bike_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
